backend_code/main/routes.py
from flask import Blueprint
from flask import render_template
from flask import request


from backend_code.models import Post


main = Blueprint('main',__name__)

#

                                            # Routes

                                        # 1. home
                                        # 2. about


                                        
@main.route("/")
@main.route("/home")
def home_text():

    page = request.args.get('page', 1, type=int)
    #Dynamic Info from database using Paginate() --> To have a limited no of posts in a single page
    blogs = Post.query.order_by(Post.date.desc()).paginate(per_page=5, page=page)
    return render_template("home_html_code.html",posts=blogs, title="Home") 

#different route for different pages
@main.route("/about")
def about_text():
    return render_template("about_html_code.html", title="About")

backend_code/posts/routes.py
from flask import Blueprint
from flask import render_template
from flask import url_for
from flask import flash
from flask import redirect
from flask import request
from flask import abort

from flask_login import current_user 
from flask_login import login_required

from backend_code import db

from backend_code.models import Post

from backend_code.posts.forms import CreatePost

posts = Blueprint('posts',__name__)


# 
                                            # Post Routes
                                        
                                        # 1. post
                                        # 2. new    post
                                        # 3. update post
                                        # 4. delete post  
        # <!-------------------------------------------------------------------------------------------------->


@posts.route("/posts/<int:post_id>")
def post(post_id):
    post_instance = Post.query.get_or_404(post_id)
    return render_template("post_html_code.html", title="Post", post=post_instance)

@posts.route("/posts/new", methods=['GET','POST'])
@login_required
def new_post():
    new_post_instance = CreatePost()
    if new_post_instance.validate_on_submit():
        blog = Post(title=new_post_instance.title.data, content=new_post_instance.content.data, author=current_user)
        db.session.add(blog)
        db.session.commit()

        flash('Your Post has been created','success')
        return redirect(url_for('main.home_text'))
    return render_template("create_post_html_code.html", title="New Post", form=new_post_instance, legend="New Post")

# We did not create a separate form and template to update the post
# Rather just made changes to create_post template through a legend
# We just used the create post form too

@posts.route("/posts/<int:post_id>/update", methods=['GET','POST'])
@login_required
def update_post(post_id):
    
    update_post_instance = Post.query.get_or_404(post_id)
    
    if update_post_instance.author != current_user:
        abort(403)
    
    update_form   = CreatePost()
    
    if update_form.validate_on_submit():
        update_post_instance.title   = update_form.title.data
        update_post_instance.content = update_form.content.data
        db.session.commit()
        flash('Updated Changes Successfully', 'success')
        return redirect(url_for('posts.post', post_id=update_post_instance.id))

    elif request.method == 'GET':
        update_form.title.data   = update_post_instance.title
        update_form.content.data = update_post_instance.content
    return render_template("create_post_html_code.html", title="Update Post", form=update_form, legend="Update Post" )

@posts.route("/posts/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    
    delete_post_instance = Post.query.get_or_404(post_id)
    
    if delete_post_instance.author != current_user:
        abort(403)
    db.session.delete(delete_post_instance)
    db.session.commit()
    flash('Post Deleted Successfully', 'danger')
    return redirect(url_for('main.home_text'))

backend_code/users/routes.py
from flask import Blueprint
from flask import render_template
from flask import url_for
from flask import flash
from flask import redirect
from flask import request

from flask_login import login_user
from flask_login import current_user 
from flask_login import logout_user
from flask_login import login_required

from backend_code import db
from backend_code import bcrypt

from backend_code.models import User
from backend_code.models import Post

from backend_code.users.forms import RegistrationForm
from backend_code.users.forms import LoginForm
from backend_code.users.forms import UpdateForm
from backend_code.users.forms import RequestResetForm
from backend_code.users.forms import ResetPasswordForm


from backend_code.users.utils import save_picture 
from backend_code.users.utils import send_email

users = Blueprint('users',__name__)

#

                                            # Routes

                                        # 1. register
                                        # 2. login
                                        # 3. logout
                                        # 4. account 
                                        # 5. user_posts


@users.route("/register", methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home_text'))
    else:
        form_instance = RegistrationForm()
        if form_instance.validate_on_submit():

            #hash the password and save it to database
            hashed_pw = bcrypt.generate_password_hash(form_instance.password.data).decode('utf-8')
            user = User(username=form_instance.username.data, email=form_instance.email.data, password=hashed_pw)
            db.session.add(user)
            db.session.commit()

            #flash a message and redirect to login page
            flash("Account Created Successfully", 'success')
            return redirect(url_for('users.login'))
        return render_template('register_html_code.html', title="Register", form=form_instance)

@users.route("/login", methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home_text'))
    else:
        login_instance = LoginForm()
        if login_instance.validate_on_submit():

            user = User.query.filter_by(email=login_instance.email.data).first()
            if user and bcrypt.check_password_hash(user.password, login_instance.password.data):
                login_user(user, remember=login_instance.remember.data)
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('main.home_text'))
            else:
                flash("Login Incorrect", 'danger') 
        return render_template('login_html_code.html', title="Login", form=login_instance)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home_text'))


@users.route('/account', methods=['GET','POST'])
@login_required
def account():
    account_instance = UpdateForm()
    if account_instance.validate_on_submit():
        if account_instance.picture.data:
            picture_file = save_picture(account_instance.picture.data)
            current_user.image_file = picture_file

        current_user.username = account_instance.username.data
        current_user.email = account_instance.email.data
        db.session.commit()
        flash('Your Account has been upadted','success')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        account_instance.username.data = current_user.username
        account_instance.email.data = current_user.email

    image_file = url_for('static', filename='pics/' + current_user.image_file)
    return render_template('account_html_code.html', title="Account", form=account_instance, image_file=image_file)

@users.route("/user/<string:username>")
def user_posts(username):

    page = request.args.get('page', 1, type=int)
    user_instance = User.query.filter_by(username=username).first_or_404()

    blogs = Post.query\
        .filter_by(author=user_instance)\
        .order_by(Post.date.desc())\
        .paginate(per_page=5, page=page)
    

    return render_template("user_posts_html_code.html",posts=blogs, title="User Posts", user=user_instance) 



# 
                                            # Password Routes
                                        
                                        # 6. reset request
                                        # 7. reset password
        # <!-------------------------------------------------------------------------------------------------->



@users.route("/reset_password", methods=["GET","POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home_text'))
    request_instance = RequestResetForm()
    if request_instance.validate_on_submit():
        user = User.query.filter_by(email=request_instance.email.data).first()
        
        #Now we will send user the email
        send_email(user)
        flash('A mail has been sent to your Email Account', 'info')
        return redirect(url_for('users.login'))


    return render_template('reset_request_html_code.html', title="Reset Password", form=request_instance)

@users.route("/reset_password/<token>", methods=["GET","POST"])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home_text'))
    user = User.verify_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    
    
    password_instance = ResetPasswordForm()
    if password_instance.validate_on_submit():

        #hash the password and save it to database
        hashed_pw = bcrypt.generate_password_hash(password_instance.password.data).decode('utf-8')
        user.password = hashed_pw
        db.session.commit()

        #flash a message and redirect to login page
        flash("Reset Password Successfully", 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_password_html_code.html', title="Reset Password", form=password_instance)

backend_code/templates/about_html_code.html
{% extends "root_template.html" %}
{% block content %}


    <p>THis is About page</p>


{% endblock content %}




















<!---

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">



    {% if title %}
        <title> {{ title }}</title>
    {% else %}
        <title>About Page</title>
    {%endif%}
    


</head>
<body>
    <h1>THis is About page</h1>
</body>
</html>
-->

backend_code/templates/account_html_code.html
{% extends "root_template.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
        <img class="rounded-circle account-img" src= {{image_file}}>
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
            <br><br><br><br><br><br><br>
        </div>
        </div>
        <!-- FORM HERE -->
        <!--- <div class="content-section">   -->
            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Update Account Info </legend>
    
    
                    
                    <div class="form-group"> 
                        {{ form.username.label(class="form-control-label") }}
                            {% if form.username.errors %}
                                {{ form.username(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.username.errors %}
                                        <span> {{ error }} </span>
                                        {% endfor %}
                                    </div>
                            {% else %}
                                {{ form.username(class="form-control form-control-lg ") }}
                            {% endif%}
                    </div>
                    
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                            {% if form.email.errors %}
                                {{ form.email(class="form-control  form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.email.errors %}
                                        <span> {{ error }} </span>
                                        {% endfor %}
                                    </div>
                            {% else %}
                                {{ form.email(class="form-control  form-control-lg ") }}
                            {% endif %}
                    </div>

                    <!--- PICTURE -->
                    <div class="form-group">
                        {{ form.picture.label() }}
                        {{ form.picture(class="form-control-file") }}
                        {% if form.picture.errors %}    
                            {% for error in  form.picture.errors %}
                                <span class="text-danger"> {{ error }} </span><br> 
                            {% endfor %}
                        {% endif %}
                    </div>









                </fieldset>
    
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info" ) }}
                </div>


            </form>
        <!-- </div> -->
    </div>
{% endblock content %}

backend_code/templates/create_post_html_code.html
{% extends "root_template.html" %}
{% block content %}

    <div class="content-section">  
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"> {{ legend }} </legend>


                

                
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                        {% if form.title.errors %}
                            {{ form.title(class="form-control  form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.title.errors %}
                                    <span> {{ error }} </span>
                                    {% endfor %}
                                </div>
                        {% else %}
                            {{ form.title(class="form-control  form-control-lg ") }}
                        {% endif %}
                </div>
                
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                        {% if form.content.errors %}
                            {{ form.content(class="form-control  form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.content.errors %}
                                    <span> {{ error }} </span>
                                    {% endfor %}
                                </div>
                        {% else %}
                            {{ form.content(class="form-control  form-control-lg ") }}
                        {% endif %}
                </div>



            </fieldset>

            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info" ) }}
            </div>

        </form>
    </div>

{% endblock content %}

backend_code/templates/home_html_code.html
{% extends "root_template.html" %}
{% block content %}

  

    {% for i in posts.items %}
    
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='pics/' + i.author.image_file) }}">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href=" {{ url_for('users.user_posts', username=i.author.username) }} ">{{ i.author.username }}</a>
            <small class="text-muted">{{ i.date.strftime('%d-%m-%Y') }}</small>
          </div>
          <h2><a class="article-title" href="{{ url_for('posts.post', post_id=i.id)}}">{{ i.title }}</a></h2>
          <p class="article-content">{{ i.content }}</p>
        </div>
    </article>
    
    {%endfor%}
    <!-- edge means side -->
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
        {% if page_num %}
            
            {% if posts.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('main.home_text', page=page_num) }}" > {{ page_num }} </a>
            {% else %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home_text', page=page_num) }}"> {{ page_num }} </a>
            {% endif %}
        
        
        {% else %}
            ...
        {% endif %}
    {% endfor %}

{% endblock content %}

backend_code/templates/login_html_code.html
{% extends "root_template.html"%}
{% block content %}

    <div class="content-section">  
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"> Login </legend>


                
    
                
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control  form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                    <span> {{ error }} </span>
                                    {% endfor %}
                                </div>
                        {% else %}
                            {{ form.email(class="form-control  form-control-lg ") }}
                        {% endif %}
                </div>
                
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control  form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                    <span> {{ error }} </span>
                                    {% endfor %}
                                </div>
                        {% else %}
                            {{ form.password(class="form-control  form-control-lg ") }}
                        {% endif %}
                </div>

                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    &ensp;
                    {{ form.remember.label(class="form-check-label")}}
                </div>

            
                




            </fieldset>

            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info" ) }}
            </div>

            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}"> Forgot Password ?? </a>
            </small>


        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Don't have an account? <a class="ml-2" href="{{ url_for('users.register') }}"> Register Now </a>
        </small>
    </div>



{% endblock %}

backend_code/templates/post_html_code.html
{% extends "root_template.html" %}
{% block content %}

    <!--
    <h3>Started Project 1</h3>
    <h3>Static Info</h3>
    <br><br><br>   

    {% for i in posts %}
        <h1>    {{ i.title }}</h1>
        <P> By {{ i.name }} on {{ i.date }} </P>
        <p> {{ i.content }}</P>
        
        <br><br><br>
    {%endfor%}  -->

    
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='pics/' + post.author.image_file) }}">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date.strftime('%d-%m-%Y') }}</small>
            {% if post.author == current_user %}
                
                <!--  Update Post -->
                <div>
                  <a class="btn btn-secondary btn-sm m-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>

                <!--- Delete Post -->
                
                  <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>
            {% endif %}
          </div>
          <h2 class="article-title">{{ post.title }}</a></h2>
          <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
              <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div> 

{% endblock content %}

backend_code/templates/reset_password_html_code.html
{% extends "root_template.html"%}
{% block content %}

    <div class="content-section">  
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"> Reset Password </legend>    
                
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control  form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                    <span> {{ error }} </span>
                                    {% endfor %}
                                </div>
                        {% else %}
                            {{ form.password(class="form-control  form-control-lg ") }}
                        {% endif %}
                </div>
                
                <div class="form-group">
                    {{ form.confirm.label(class="form-control-label") }}
                        {% if form.confirm.errors %}
                            {{ form.confirm(class="form-control  form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.confirm.errors %}
                                    <span> {{ error }} </span>
                                    {% endfor %}
                                </div>
                        {% else %}
                            {{ form.confirm(class="form-control  form-control-lg ") }}
                        {% endif %}
                </div>

            </fieldset>

            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info" ) }}
            </div>


        </form>
    </div>


{% endblock %}

backend_code/templates/root_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!--
        BEFORE BOOTSTRAP
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    -->
     




    <!----------------------------------------------------------------------------->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    
    
                    <!-------------------------------------->
                    <!-------------------------------------->
    
    <!--- OUR CUSTOM CSS LINK -->

    <!--   folder name >> static
           file   name >> main.css    -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static' , filename='main.css') }}">

                    <!-------------------------------------->
                    <!-------------------------------------->
    
    <!------------------------------------------------------------------------------->












    {% if title %}
        <title> {{ title }}</title>
    {% else %}
        <title> Flask </title>
    {%endif%}
    


</head>
<body>

    
    
    
    <!--------------------------------------------------------------------------------->
    
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">Flask Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.home_text') }}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('main.about_text') }}">About</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>

                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}

              </div>
            </div>
          </div>
        </nav>
      </header>

    <!---------------------------------------------------------------------------->
    <!---<div class="container">{% block P_1 %} {% endblock %} </div> -->
    <!---------------------------------------------------------------------------->
    <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
          </div>
          <div class="col-md-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div>
          </div>
        </div>
    </main>
    <!---------------------------------------------------------------------------->






    <!-- BOOTSTRAP JS -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- ENDED  -->

</body>
</html>

backend_code/templates/user_posts_html_code.html
{% extends "root_template.html" %}
{% block content %}

    <h2 class="mb-3">
        Posts by {{ user.username }}  - <small>({{ posts.total }}) </small>
    </h2>




    {% for i in posts.items %}
    
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='pics/' + i.author.image_file) }}">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="#">{{ i.author.username }}</a>
            <small class="text-muted">{{ i.date.strftime('%d-%m-%Y') }}</small>
          </div>
          <h2><a class="article-title" href="{{ url_for('posts.post', post_id=i.id)}}">{{ i.title }}</a></h2>
          <p class="article-content">{{ i.content }}</p>
        </div>
    </article>
    
    {%endfor%}
    <!-- edge means side -->
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
        {% if page_num %}
            
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}" > {{ page_num }} </a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}" > {{ page_num }} </a>
            {% endif %}
        
        
        {% else %}
            ...
        {% endif %}
    {% endfor %}





{% endblock content %}